# Generated by Django 4.1.4 on 2022-12-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('artist', models.CharField(max_length=80)),
                ('spotify_link', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('youtube_link', models.CharField(max_length=100)),
            ],
        ),
    ]
