# Generated by Django 4.1.4 on 2022-12-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("last_updated", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Songs",
            fields=[
                ("name", models.CharField(max_length=500)),
                ("artist", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "spotify_link",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "preview_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "playlist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.playlists",
                    ),
                ),
            ],
        ),
    ]
