# Generated by Django 4.1.4 on 2022-12-22 22:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistList",
            fields=[
                (
                    "name",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("last_updated", models.DateField()),
                ("list", models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="Artists",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=500, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                ("spotify_link", models.CharField(max_length=500)),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                ("followers", models.IntegerField(default=True, null=True)),
                (
                    "last_updated",
                    models.DateField(
                        blank=True, default=django.utils.timezone.now, null=True
                    ),
                ),
                (
                    "artist_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to="core.artistlist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Playlists",
            fields=[
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("last_updated", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Songs",
            fields=[
                (
                    "id",
                    models.CharField(
                        default="", max_length=500, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=500)),
                (
                    "artist",
                    models.CharField(
                        blank=True, default=None, max_length=500, null=True
                    ),
                ),
                ("spotify_link", models.CharField(max_length=500)),
                (
                    "preview_url",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                ("popularity", models.IntegerField(blank=True, null=True)),
                (
                    "artist_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="toptracks",
                        to="core.artists",
                    ),
                ),
                (
                    "playlist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tracks",
                        to="core.playlists",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="artists",
            name="top_album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="artist",
                to="core.playlists",
            ),
        ),
    ]
