# Generated by Django 4.1.4 on 2022-12-19 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="songs",
            name="youtube_link",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
