# Generated by Django 4.1.4 on 2023-01-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_songs_playlist_rank"),
    ]

    operations = [
        migrations.AddField(
            model_name="songs",
            name="lyrics",
            field=models.TextField(blank=True, null=True),
        ),
    ]
