# Generated by Django 4.1.4 on 2022-12-17 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_song_songs'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='preview_url',
            field=models.CharField(default='null', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='spotify_link',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='songs',
            name='youtube_link',
            field=models.CharField(max_length=500),
        ),
    ]
