# Generated by Django 4.1.4 on 2022-12-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_songs_preview_url_alter_songs_spotify_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songs',
            name='artist',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songs',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='songs',
            name='preview_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='songs',
            name='youtube_link',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
