# Generated by Django 4.1.4 on 2022-12-21 22:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_songs_youtube_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArtistList",
            fields=[
                (
                    "name",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("last_updated", models.DateField()),
                ("list", models.CharField(max_length=50000)),
            ],
        ),
        migrations.CreateModel(
            name="Artists",
            fields=[
                ("name", models.CharField(max_length=500)),
                (
                    "spotify_link",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "youtube_link",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("image_url", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "artist_list",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to="core.artistlist",
                    ),
                ),
                (
                    "top_album",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artist",
                        to="core.playlists",
                    ),
                ),
            ],
        ),
    ]
