# Generated by Django 4.1.4 on 2022-12-21 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_artistlist_artists"),
    ]

    operations = [
        migrations.AddField(
            model_name="artists",
            name="popularity",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
