# Generated by Django 4.1.4 on 2022-12-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_artists_popularity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artists",
            name="spotify_link",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="songs",
            name="spotify_link",
            field=models.CharField(max_length=500),
        ),
                migrations.AddField(
            model_name="artists",
            name="id",
            field=models.CharField(
                default="", max_length=500, primary_key=True, serialize=False
            ),
        ),
        migrations.AddField(
            model_name="songs",
            name="id",
            field=models.CharField(
                default="", max_length=500, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="songs",
            name="artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.artists",
            ),
        ),
    ]
